version: 2.1

orbs:
  haskell-build: haskell-works/haskell-build@4.1.9

workflows:
  build-my-library:
    jobs:
      - haskell/build-with-cci-cache:
          executor: haskell/ghc-8_10_7
          name: GHC 8.10.7