version: 2

jobs:
  build_project:
    machine: true
    steps:
      - checkout
      - restore-cache:
          keys:
            - stack-{{ checksum “stack.yaml” }}
      - restore-cache:
          keys:
            - stack-{{checksum “stack.yaml”}}-{{checksum “project.cabal”}}
      - run: wget https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-freebsd-x86_64.tar.gz -O /tmp/stack.tar.gz
      - run: sudo mkdir /tmp/stack-download
      - run: sudo tar -xzf /tmp/stack.tar.gz -C /tmp/stack-download
      - run: sudo chmod +x /tmp/stack-download/stack-1.6.1-linux-x86_64/stack
      - run: sudo mv /tmp/stack-download/stack-1.6.1-linux-x86_64/stack /usr/bin/stack
      - run: stack setup
      - run: stack test
      - save-cache:
          key: stack-{{ checksum “stack.yaml” }}
          paths:
            - "~/.stack"
      - save-cache:
          key: stack-{{checksum “stack.yaml”}}-{{checksum “project.cabal”}}
          paths:
            - ".stack-work"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_project
