name: build-language-ocaml
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["8.10.7"] # , "9.0.1"]
        cabal: ["latest"]
        os: [ubuntu-latest] # , macOS-latest, windows-latest]
        exclude:
          # GHC 8.8+ only works with cabal v3+
          - ghc: 8.8.3
            cabal: 2.4.1.0
    name: ${{ matrix.os }} cabal-${{ matrix.cabal }} ghc-${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal update
      - run: cabal build language-ocaml
      - run: cabal test language-ocaml
